version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    - '443:443'
    expose:
      - 80
      - 443
    volumes:
      - .:/var/www
      - ./.devcontainer/nginx.conf:/etc/nginx/nginx.conf
      - ./.devcontainer/server.crt:/etc/nginx/server.crt
      - ./.devcontainer/server.csr:/etc/nginx/server.csr
      - ./.devcontainer/server.key:/etc/nginx/server.key
      - ./.devcontainer/openssl.cnf:/etc/nginx/openssl.cnf

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - "redis:/data"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          memory: 500M

volumes:
  redis: