import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql } from "@apollo/client";

import client from "../lib/apollo";
import styles from '../styles/Home.module.css'

export type HomeProps = {
  posts: any[]
}

const Home: NextPage<HomeProps> = ({posts}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {posts?.map(post => (
            <a href="#" className={styles.card}>
              <h2>{post.name} &rarr;</h2>
              <p>{post.id} : {post._id}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
        query Posts {
          posts {
            id
            _id
            name
          }
        }
      `,
  });

  return {
    props: {
      posts: data.posts,
    },
  };
}

export default Home
